### ISSUE TITLE
Link Lists are borked!

### ISSUE THREAD

**Issue by AABoyles** [CDCgov/MicrobeTrace#10]
Link lists are exhibiting a show-stopping bug whereby they don't display at all.

**Comment by AABoyles** [comment]
I believe this was resolved by e6a0fd7cf8b3ad290fedfe22036879ad9b46ab12, but it's a little hard to test.

**Comment by rlechtenberg** [comment]
Looks to me like the issue persists. When I load the edge list in the first screenshot below into MicrobeTRACE, I get a network without any edges connecting nodes (see second screenshot):

![image](https://user-images.githubusercontent.com/38964413/46505590-607cd780-c7e6-11e8-807c-e9cd7b4dc6c1.png)

![image](https://user-images.githubusercontent.com/38964413/46505598-6d99c680-c7e6-11e8-9a08-ac1e80533c65.png)
