### ISSUE TITLE
Cytoscape: Grouping color key table and shape table bug 

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTRACE#937]
After I group by a variable, and try changing colors, it has multiple issues, it turns some blocks white, and some of them the key table no longer matches the actual color of the group.

Also, I changed the shapes to my preference and assigned certain shapes to certain categories. e.g Empty was triangle. But as I was playing with my data, I noticed that MT swapped the shapes. Empty is now squares.
Some issue with key tables matching the network perhaps?

**Comment by dacowan404** [comment]
Deployed to mossy 05/28/2025; please retest;
Changing colors of groups should now target the expected groups;
'Some blocks are white/clear', Based on the session file settings: One polygon (International University) will show up clear on loading based on opacity value in session file. Similarly, another will show up opaque due to the settings in this file. However, adjusting the slide works as expected now.
For Node Shapes, it should now be properly loading the shapes from the session file. Updated MT Angular to store shape assignments the same way as MT Classic.

**Comment by ikb6** [comment]
The color change on groups is still not working. I used the built in dataset to test, and colored groups by State. 
See image below. It repeated the color blue for Texas and Connecticut, so I clicked on the bar for Connecticut to change it, but it changed Texas. The key table does not match what it actually does.

<img width="1680" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0ZDQ2c9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1bd8437241d8161e3f66804e2d7acd886cac12ef/image.png" alt="image.png" />

**Comment by billswitzer2** [comment]
Yikes!

**Comment by dacowan404** [comment]
Resolved the issue with updated group colors; pushed to dev 6/6/2025

**Comment by ikb6** [comment]
Sorry, but this is still not great. 
1. The default colors picked are basically diff shades of the same color, and that is probably not good from an accessibility perspective. PA, AZ and TX are almost the same
2. There seems to be a transparency mismatch between the groups and the little blocks in the key table. See image 
below. The color of Pennsylvania is light, and so is FL, but see the dark color in the key table. It's confusing if they are diff shades and diff transparencies.
3. On a positive note, the original bug is fixed. Now I can change the color of a group and it updates the table correctly

<img width="1210" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEJkQ2c9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d738b3a58e336950559058f94a1c7a465cd78e1a/image.png" alt="image.png" />

**Comment by dacowan404** [comment]
1. Update colors of groups to be more unique, updated order of the node colors to prevent similar colors from being 
next to each other (i.e. previously most of the first 10 colors were shades of blue and green).
2. Update the color shown in the table to incorporate transparency value to more accurately represent the color that appears in the network. This affects group color, link color, and node color tables. This is also included when exporting the tables.

Pushed to DEV on 06/23/25. Please retest

**Comment by ikb6** [comment]
David working on sorting first and then assign colors

**Comment by dacowan404** [comment]
Updated code to sort groups based on count first and then assign colors;
Pushed to dev 7/28/25
